// shared/types/athlete.ts

import { DataCard } from './dataCard';

export interface Athlete {
  _id?: string; // Optional, generated by MongoDB
  firstName: string;
  lastName: string;
  year: 'Freshman' | 'Sophomore' | 'Junior' | 'Senior';
  sports: string;
  portraitPhoto: string;
  actionPhoto?: string;
  biography?: string;
  portfolioData?: DataCard[]; // Now a single array of DataCard objects
  isDeleted?: boolean;
}
